config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "prototypes#index"
  resources :prototypes do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '洗顔料' },
    { id: 3, name: 'クレンジング' },
    { id: 4, name: '化粧水' },
    { id: 5, name: '乳液、美容液' },
    { id: 6, name:   'オールインワン' },
    { id: 7, name: 'パック、フェイスマスク' },
    { id: 8, name: 'その他スキンケア' }, 
  ]

  include ActiveHash::Associations
  has_many :prototypes
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :prototype

  validates :content, presence: true

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :prototype
end

app/models/prototype.rb
class Prototype < ApplicationRecord
  belongs_to :user
  has_many   :comments, dependent: :destroy
  has_many   :likes,    dependent: :destroy

  


  has_one_attached :image

  with_options presence: true do
  validates :name           
  validates :recommendation
  validates :explanation
  validates :category_id
  validates :image
  end   

  validates :category_id, numericality: { other_than: 1 }

  def self.search(search)
    if search != ""
      Prototype.where('recommendation LIKE(?)', "%#{search}%")
    else
      Prototype.all
    end
  end
end

app/models/skin.rb
class Skin < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '普通肌' },
    { id: 3, name: '脂性肌' },
    { id: 4, name: '乾燥肌' },
    { id: 5, name: '混合肌' },
   
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  
  belongs_to :year
  belongs_to :skin
  has_many   :prototypes
  has_many   :comments
  has_many   :likes, dependent: :destroy

  with_options presence: true do
  validates :nickname
  validates :year_id
  validates :skin_id
  end

  with_options numericality: { other_than: 1  } do
  validates :year_id
  validates :skin_id
  end

  def liked_by?(prototype_id)
    likes.where(prototype_id: prototype_id).exists?  
  end




end

app/models/year.rb
class Year < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '10代' },
    { id: 3, name: '20代' },
    { id: 4, name: '30代' },
    { id: 5, name: '40代' },
    { id: 6, name: '50代' },
    { id: 7, name: '60代' }, 
  ]

  include ActiveHash::Associations
  has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth


  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :year_id, :skin_id])
  end
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  # 環境変数を読み込む記述に変更
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to prototype_path(@comment.prototype)
    else
      @prototype = @comment.prototype
      @comments = @prototype.comments
      render "prototypes/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, prototype_id: params[:prototype_id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :prototype_params
  def create
   Like.create(user_id: current_user.id, prototype_id: params[:id])
   render 'create.js.erb'
  end

  def destroy
   Like.find_by(user_id: current_user.id, prototype_id: params[:id]).destroy
   render 'destroy.js.erb'
  end
 
  
 private

 def prototype_params 
  @prototype = Prototype.find(params[:id])
 end

end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_prototype, only: [:show, :edit, :update, :destroy]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]

  def index
    @prototypes = Prototype.includes(:user)
  end

  def new
    @prototype = Prototype.new
  end

  def create
    @prototype = Prototype.new(prototype_params)
    if @prototype.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @prototype.comments.includes(:user)
    
  end

  def edit
  end

  def update
    if @prototype.update(prototype_params)
      redirect_to prototype_path
    else
      render :edit
    end
  end

 def destroy
   @prototype.destroy
   redirect_to root_path
 end

 def search
  @prototypes = Prototype.search(params[:keyword])
 end
  private

  def prototype_params
    params.require(:prototype).permit(:name, :recommendation, :explanation, :category_id, :image).merge(user_id: current_user.id)
  end

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @prototype.user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @prototype = @user.prototypes
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ProtoSpace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
        <script type="text/javascript" src="https://js.pay.jp/v2/pay.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("My project-1 (1).png", class: :logo), root_path %>
          </div>
          
            <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to " 投稿", new_prototype_path, class: :nav__btn %>
            </div>
           <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
           <% end  %>
          
        </div>
      </div>
     <div>
        <%# <%= form_with(url: search_prototypes_path, local: true, method: :get, class: "search-form") do |form| %>
        <%# <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %> %>
        <%# <%= form.submit "検索", class: "search-btn" %> %>
        <%# <% end %> %> %>
     <ul class= "janl">
     <li>
  <%= link_to " メンズスキンケア", '###', class: :nav__btnsv, id: :pull_down %>
   <ul class="show-lists hidden" id="lists" >
      <li class="setmen">男の肌の悩み</li>
      <li class="setmen">メンズスキンケア商品</li>
      <li class="setmen">男のスペシャルケア</li>
    </ul>
     </li>
     <li>
       <%= link_to "メンズメイク ", '###', class: :nav__btnsv, id: :pull_down_one %>
      <ul class="show-lists hidden" id="lists_one" >
      <li class="setmen">メンズメイク方法</li>
      <li class="setmen">男を磨くコスメ情報</li>
    </ul>
       </li>
     <li>
      <%= link_to "メンズヘア ", '###', class: :nav__btnsv, id: :pull_down_two %>
       <ul class="show-lists hidden" id="lists_two" >
      <li class="setmen">男のヘアセット・スタイル</li>
      <li class="setmen">男のヘアトラブル・ケア</li>
    </ul>
     </li>
     <li>
     <%= link_to "メンズボディ ", '###', class: :nav__btnsv, id: :pull_down_three %>
      <ul class="show-lists hidden" id="lists_three" >
      <li class="setmen">男のダイエット</li>
      <li class="setmen">男のボディケア</li>
    </ul>
     </li>
     </ul>
     
     </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? && current_user.liked_by?(prototype.id) %>
         <div><%= link_to '❤️', destroy_like_path(prototype.id), method: :DELETE, class: "tweet_likes", remote: true  %><%= prototype.likes.count %></div>
         <% else %>
         <div><%= link_to '♡', create_like_path(prototype.id), method: :POST, class: "tweet_likes", remote: true  %><%= prototype.likes.count %></div>
         <% end %>

app/views/likes/create.js.erb
document.getElementById('like-btn<%= @prototype.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {prototype: @prototype}) %>"

app/views/likes/destroy.js.erb
document.getElementById('like-btn<%= @prototype.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {prototype: @prototype}) %>"

app/views/prototypes/ search.html.erb
<%= form_with(url: search_prototypes_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @prototypes.each do |prototype| %>
    <%= render partial: "prototype", locals: { prototype: prototype } %>
  <% end %>
</div>

app/views/prototypes/_form.html.erb
<%= form_with model: prototype, local: true do |f|%>
  <div class="field">
    <%= f.label :name, "商品名" %><br />
    <%= f.text_field :name, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :recommendation, "おすすめ" %><br />
    <%= f.text_area :recommendation, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :explanation, "使用方法" %><br />
    <%= f.text_area :explanation, class: :form__text, id:"prototype_concept" %>
  </div>


   <div class="field">
   商品の種類<br>
   <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select"}) %>
  </div>


  <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/prototypes/_prototype.html.erb
<div class="card">
  <%= link_to image_tag(prototype.image, class: :card__img ), prototype_path(prototype.id), method: :get %>
  <div class="card__body">
    <%= link_to prototype.name, prototype_path(prototype.id), class: :card__title%>
        <%= prototype.user.year.name  %>     |
        <%= prototype.user.skin.name  %>
          <div id="like-btn<%= prototype.id %>">
           <%= render partial: "likes/like", locals: { prototype: prototype } %>
          </div>
   
    <p class="card__summary">
       <%= prototype.created_at %><br>
      <%= prototype.recommendation.truncate(50) %>
        <%= link_to "続きを読む", prototype_path(prototype.id), class: :card_num %>
    </p>
    <%= link_to "#{prototype.user.nickname}さん", user_path(prototype.user.id), class: :card__user %>
  </div>
</div>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">投稿編集</h2>
     <%= render partial: "form", locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner">
         <% if user_signed_in? %>
      <div class="greeting">
        Menz Beauty（メンズビューティー）にようこそ!
        <%= link_to "#{current_user.nickname}さん", user_path(current_user.id), class: :greeting__link %>
      </div>
      <% end %>
    <div class="wrapper">
      <div class="container">
      <div class="container__item">
      <%= image_tag("recommend_item1.png", class: :card__imgs )  %>
      </div>
      <div class="container__item">
      <%= image_tag("KkJv0hc.png", class: :card__imgs )  %>
      </div>
      <div class="container__item">
      <%= image_tag("picture_pc.png", class: :card__imgs )  %>
       </div>
      <div class="container__item">
       <%= image_tag("87412-11.png", class: :card__imgs )  %>
      </div>
      </div>
    </div>
    <div class="card__wrapper">
       <%= render partial: "prototype", collection: @prototypes %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">投稿</h2>
    <%= render partial: "form", locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @prototype.name%>
      </p>
      <%= link_to "#{@prototype.user.nickname}", user_path(@prototype.user.id), class: :prototype__user %>
        <% if user_signed_in? && current_user.id == @prototype.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_prototype_path(@prototype.id), class: :prototype__btn %>
          <%= link_to "削除する", prototype_path(@prototype.id), method: :delete, class: :prototype__btn %>
        </div>
        <% end %>
      <div class="prototype__image">
        <%= image_tag @prototype.image %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">おすすめ</p>
          <p class="detail__message">
            <%= @prototype.recommendation %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">使用方法</p>
          <p class="detail__message">
            <%= @prototype.explanation %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <% if user_signed_in? %>
          <%= form_with model: [@prototype, @comment], id: "comments-form", local: true do |f| %>
            <div class="field">
              <%= f.label :content, "コメント" %>  <br /> 
              <%= f.text_field :content, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn %>
            </div>
          <% end %>
          <% end  %>
        <% @comments.each do |comment| %>
           <li class="comments_list">
            <%= comment.content %>
           <%= link_to comment.user.nickname, user_path(comment.user.id), class: :comment_user %>
           </li>
         <% end %>
            </div>
        </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.nickname %></td>
          </tr>
          
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= @user.year.name %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= @user.skin.name %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの投稿一覧"%>
      </h2>
      <div class="user__card">
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
        <%= render partial: "prototypes/prototype", collection: @prototype  %>
      </div>
    </div>
  </div>
</div>